In [4]:
import duckdb

In [9]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [10]:
df = con.execute("SELECT * FROM produtos").fetchdf()
df.head(10)

      id nm_produto id_categoria  id_fornecedor  vl_preco
0  10004      SERRA         BT50            100     200.0
1  10005    MACHADO         BT50            100     100.0
2  10002    MARTELO         BT50            100    1500.0
3  10003      PREGO         BT10            100      60.0
4  10001   PARAFUSO         BT10            100     100.0
5  10002    MARTELO         BT50            100    1500.0
6  10001   PARAFUSO         BT10            100     100.0
7  10005    MACHADO         BT50            100     100.0
8  10004      SERRA         BT50            100     200.0
9  10003      PREGO         BT10            100      60.0

In [11]:
df2 = df.drop(columns = ['id_categoria','id_fornecedor'])
df2.head(10)

      id nm_produto  vl_preco
0  10004      SERRA     200.0
1  10005    MACHADO     100.0
2  10002    MARTELO    1500.0
3  10003      PREGO      60.0
4  10001   PARAFUSO     100.0
5  10002    MARTELO    1500.0
6  10001   PARAFUSO     100.0
7  10005    MACHADO     100.0
8  10004      SERRA     200.0
9  10003      PREGO      60.0

In [15]:
con.execute("""
    CREATE TABLE IF NOT EXISTS dim_produtos (
        id_produto BIGINT,
        nm_produto TEXT,
        vl_produto FLOAT
        )
""")

In [16]:
df_dim = con.execute("SELECT * FROM dim_produtos").fetchdf()
df_dim.head(10)

Empty DataFrame
Columns: [id_produto, nm_produto, vl_produto]
Index: []

In [ ]:
#con.execute(""" DROP TABLE dim_produtos""")

In [17]:
con.execute("INSERT INTO dim_produtos SELECT * FROM df2")

In [18]:
df_dim = con.execute("SELECT * FROM dim_produtos").fetchdf()
df_dim.head(10)

   id_produto nm_produto  vl_produto
0       10004      SERRA       200.0
1       10005    MACHADO       100.0
2       10002    MARTELO      1500.0
3       10003      PREGO        60.0
4       10001   PARAFUSO       100.0
5       10002    MARTELO      1500.0
6       10001   PARAFUSO       100.0
7       10005    MACHADO       100.0
8       10004      SERRA       200.0
9       10003      PREGO        60.0

In [19]:
con.close()